### ISSUE TITLE
Alfred sorting based on uid

### ISSUE THREAD

**Issue by kiliankoe** [pascalw/go-alfred#1]
Hi, according to the [Alfred xml docs](https://www.alfredapp.com/help/workflows/inputs/script-filter/xml/) Alfred applies it's own sorting to items based on the uid. If no sorting should be applied, uid should be completely left out.

I'm currently running into an issue, where the sortings of my items is not the order I output them, when I leave out the uid. I'm guessing this is due to the fact, that uid defaults to `""` if left out when generating a new item, which then throws off Alfred.

I'm still rather new to go, but is there a way to make the uid field completely optional? Something to add to the xml attribute [here](https://github.com/pascalw/go-alfred/blob/master/alfred.go#L17) possibly to leave it out completely if it's not set? That would be perfect.

I'm currently having to resort to generating a unique id for each item, which is somewhat of a workaround, but definitely not ideal.

**Comment by kiliankoe** [comment]
I stumbled around a bit and couldn't find anything specific to XML, but for JSON a `omitempty` attribute is supported. It seems to work just fine for XML as well when added to all the `attr`s on `AlfredResponseItem`, which seems to be correct as they're all optional. See #2.

**Comment by pascalw** [comment]
Closed via 16aeb807166cb79fe1bcf72995e14cbe882b3a9b, thanks!
